// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("StreamDeckDotnet.Fable")>]
[<assembly: AssemblyProductAttribute("StreamDeckDotnet")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-01-07T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","e748165250498ceaf81e07cada9b8c7c97020f53")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "StreamDeckDotnet.Fable"
    let [<Literal>] AssemblyProduct = "StreamDeckDotnet"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-01-07T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "e748165250498ceaf81e07cada9b8c7c97020f53"
